<a href="https://colab.research.google.com/github/BilalAsifB/Learning-PyTorch/blob/main/notebooks/00_pytorch_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
print(torch.__version__)

2.9.0+cu126


### Creating Tensors

In [2]:
# scalar

scalar = torch.tensor(7)
scalar

tensor(7)

In [3]:
scalar.ndim

0

In [4]:
scalar.item()

7

In [5]:
# vector

vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [6]:
vector.ndim

1

In [7]:
vector.shape

torch.Size([2])

In [8]:
# MATRIX

MATRIX = torch.tensor([[7, 8],
                       [6, 9]])
MATRIX

tensor([[7, 8],
        [6, 9]])

In [9]:
MATRIX.ndim

2

In [10]:
MATRIX.shape

torch.Size([2, 2])

In [11]:
MATRIX[0]

tensor([7, 8])

In [12]:
MATRIX[1]

tensor([6, 9])

In [13]:
# TENSOR

TENSOR = torch.tensor([[[1, 2, 3],
                        [4, 5, 6]],
                       [[7, 8, 9],
                        [10, 11, 12]]])
TENSOR

tensor([[[ 1,  2,  3],
         [ 4,  5,  6]],

        [[ 7,  8,  9],
         [10, 11, 12]]])

In [14]:
TENSOR.ndim

3

In [15]:
TENSOR.shape

torch.Size([2, 2, 3])

In [16]:
TENSOR[0]

tensor([[1, 2, 3],
        [4, 5, 6]])

In [17]:
TENSOR[1]

tensor([[ 7,  8,  9],
        [10, 11, 12]])

### Random tensors



In [18]:
X = torch.rand(3, 4)
X

tensor([[0.3571, 0.9540, 0.3147, 0.6009],
        [0.9186, 0.5634, 0.6764, 0.6733],
        [0.9896, 0.0328, 0.7842, 0.6542]])

In [19]:
X.ndim

2

In [20]:
X.shape

torch.Size([3, 4])

In [21]:
Y = torch.rand(size=(3, 32, 32))

In [22]:
Y.ndim

3

In [23]:
Y.shape

torch.Size([3, 32, 32])

### Zeros and Ones

In [24]:
zeros = torch.zeros(size=(3, 6))
zeros

tensor([[0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.]])

In [25]:
ones = torch.ones(size=(2, 8))
ones

tensor([[1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1.]])

In [26]:
ones.dtype

torch.float32

### Range of tensors

In [27]:
Z = torch.arange(start=0, end=11, step=2)
Z

tensor([ 0,  2,  4,  6,  8, 10])

### Datatypes

In [28]:
A = torch.tensor([1.0, 2.0], dtype=torch.half)

In [29]:
A.dtype

torch.float16

In [30]:
# float16 == torch.half
# float32 == torch.float
# float64 == torch.double

### Tensor Operations

In [31]:
X = torch.tensor([1, 2, 3])

In [32]:
X += 10

In [33]:
X

tensor([11, 12, 13])

In [34]:
X *= 10

In [35]:
X

tensor([110, 120, 130])

In [36]:
X -= 10

In [37]:
X

tensor([100, 110, 120])

In [38]:
A = torch.tensor([[1, 2],
                  [3, 4]])

In [39]:
A

tensor([[1, 2],
        [3, 4]])

In [40]:
B = torch.tensor([[5, 6],
                  [7, 8]])

In [41]:
B

tensor([[5, 6],
        [7, 8]])

In [42]:
A * B # elementwise multiplication

tensor([[ 5, 12],
        [21, 32]])

In [43]:
torch.matmul(A, B) # matrix multiplication

tensor([[19, 22],
        [43, 50]])

In [44]:
torch.mm(A, B) # shorthand name

tensor([[19, 22],
        [43, 50]])

In [45]:
A @ B

tensor([[19, 22],
        [43, 50]])

In [46]:
%%time
A @ B

CPU times: user 0 ns, sys: 34 µs, total: 34 µs
Wall time: 37.7 µs


tensor([[19, 22],
        [43, 50]])

In [47]:
%%time
torch.matmul(A, B)

CPU times: user 32 µs, sys: 5 µs, total: 37 µs
Wall time: 40.3 µs


tensor([[19, 22],
        [43, 50]])

In [48]:
# The time is almost same as '@' is an alternate.

### Aggregation functions

In [49]:
torch.min(A) # or A.min()

tensor(1)

In [50]:
torch.max(A) # or A.max()

tensor(4)

#### Code:

```
torch.mean(A)
```
#### Error:

RuntimeError                              Traceback (most recent call last)
/tmp/ipython-input-3715754511.py in <cell line: 0>()
----> 1 torch.mean(A)

RuntimeError: mean(): could not infer output dtype. Input dtype must be either a floating point or complex dtype. Got: Long

In [51]:
A = A.to(torch.float)

In [52]:
torch.mean(A) # or A.mean()

tensor(2.5000)

In [53]:
torch.sum(A) # or A.sum()

tensor(10.)

In [54]:
torch.argmin(A) # or A.argmin()

tensor(0)

In [55]:
torch.argmax(A) # or A.argmax()

tensor(3)

### Reshaping, Stacking, Squeezing, and Unsqueezing tensors

In [56]:
X = torch.arange(1, 10, dtype=torch.float)

In [57]:
X

tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [58]:
X.reshape(3, 3)

tensor([[1., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.]])

In [59]:
X.reshape(9, 1)

tensor([[1.],
        [2.],
        [3.],
        [4.],
        [5.],
        [6.],
        [7.],
        [8.],
        [9.]])

In [60]:
X.view(1, 3, 3) # view of a tensor shares the same memory
                # with the input, so if I allocate X.view(1, 3,
                # 3) to a new variable Z. If I make a change to
                # Z, X will also change. Reshape doesn't do that!

tensor([[[1., 2., 3.],
         [4., 5., 6.],
         [7., 8., 9.]]])

In [61]:
torch.stack([X, X], dim=0)

tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.],
        [1., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [62]:
torch.stack([X, X], dim=1)

tensor([[1., 1.],
        [2., 2.],
        [3., 3.],
        [4., 4.],
        [5., 5.],
        [6., 6.],
        [7., 7.],
        [8., 8.],
        [9., 9.]])

In [63]:
Z = X.reshape(1, 3, 3)

In [64]:
torch.stack([Z, Z], dim=2)

tensor([[[[1., 2., 3.],
          [1., 2., 3.]],

         [[4., 5., 6.],
          [4., 5., 6.]],

         [[7., 8., 9.],
          [7., 8., 9.]]]])

In [65]:
torch.hstack([X, X])

tensor([1., 2., 3., 4., 5., 6., 7., 8., 9., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [66]:
torch.vstack([X, X])

tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.],
        [1., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [67]:
C = X.reshape([1, 9])

In [68]:
C.shape

torch.Size([1, 9])

In [69]:
squeezed_C = C.squeeze()

In [70]:
squeezed_C.shape

torch.Size([9])

In [71]:
squeezed_C

tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [72]:
unsqueezed_C = squeezed_C.unsqueeze(dim=1)

In [73]:
unsqueezed_C.shape

torch.Size([9, 1])

In [74]:
unsqueezed_C

tensor([[1.],
        [2.],
        [3.],
        [4.],
        [5.],
        [6.],
        [7.],
        [8.],
        [9.]])

In [75]:
D = torch.rand(size=(64, 32, 3))

In [76]:
# permute returns a view of rearanged dimensions as specified.
torch.permute(D, (2, 0, 1)).shape

torch.Size([3, 64, 32])

### Indexing

In [77]:
X = torch.arange(1, 10).reshape([1, 3, 3])

In [78]:
X

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [79]:
X[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [80]:
X[0, 0]

tensor([1, 2, 3])

In [81]:
X[0, 0, 0] # dim=0, dim=1, dim=2 ....

tensor(1)

#### Code:
```
X[1]
```
#### Error:
IndexError                                Traceback (most recent call last)
/tmp/ipython-input-1238068035.py in <cell line: 0>()
----> 1 X[1]

IndexError: index 1 is out of bounds for dimension 0 with size 1

#### Explaination:
The first dimension for this particular tensor, X, only has the shape 1 so as PyTorch is 0 indexed you can't access index 1 for this dimension in this case.

In [82]:
X[:, 0:2, 1:]

tensor([[[2, 3],
         [5, 6]]])

#### PyTorch and Numpy

In [83]:
array = np.arange(1., 10.)

In [84]:
array

array([1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [85]:
tensor = torch.from_numpy(array).type(torch.float)
# converting to float32 because Numpy's default dtype is float64
array.dtype, tensor.dtype

(dtype('float64'), torch.float32)

In [86]:
tensor = torch.arange(1., 8.)

In [87]:
tensor

tensor([1., 2., 3., 4., 5., 6., 7.])

In [88]:
array = tensor.numpy()
array.dtype, tensor.dtype

(dtype('float32'), torch.float32)

In [89]:
# The array and tensor don't share memory

#### Reproducibility

In [90]:
A = torch.rand(3, 4)
B = torch.rand(3, 4)

print(A, '\n', B, '\n', A == B)

tensor([[0.7106, 0.7932, 0.0011, 0.4478],
        [0.7942, 0.9101, 0.4568, 0.6850],
        [0.1263, 0.0165, 0.2437, 0.0836]]) 
 tensor([[0.0318, 0.3995, 0.9177, 0.8477],
        [0.4578, 0.3980, 0.7770, 0.0728],
        [0.4957, 0.8198, 0.9351, 0.9927]]) 
 tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [91]:
# set random seed
RANDOM_SEED = 42

# NOTE: The seed has to be set after every random function call

In [92]:
torch.manual_seed(RANDOM_SEED)
A = torch.rand(3, 4)
torch.manual_seed(RANDOM_SEED)
B = torch.rand(3, 4)

print(A, '\n', B, '\n', A == B)

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]]) 
 tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]]) 
 tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


#### Device agnostic code

In [93]:
device = 'cuda' if torch.cuda.is_available() else 'cpu'

#### Putting the tensors (and models) on GPU

In [94]:
tensor = torch.tensor([0, 1, 2, 3])

In [95]:
tensor_on_gpu = tensor.to(device)

In [96]:
tensor_on_gpu

tensor([0, 1, 2, 3], device='cuda:0')

In [99]:
tensor_on_cpu = tensor_on_gpu.cpu() # might need to do this if
                                    # converting to numpy because
                                    # numpy doesn't use GPU

In [100]:
tensor_on_cpu

tensor([0, 1, 2, 3])

In [102]:
array = tensor_on_cpu.numpy()