<a href="https://colab.research.google.com/github/BilalAsifB/Learning-PyTorch/blob/main/notebooks/00_pytorch_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
print(torch.__version__)

2.9.0+cpu


### Creating Tensors

In [2]:
# scalar

scalar = torch.tensor(7)
scalar

tensor(7)

In [3]:
scalar.ndim

0

In [4]:
scalar.item()

7

In [5]:
# vector

vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [6]:
vector.ndim

1

In [7]:
vector.shape

torch.Size([2])

In [8]:
# MATRIX

MATRIX = torch.tensor([[7, 8],
                       [6, 9]])
MATRIX

tensor([[7, 8],
        [6, 9]])

In [9]:
MATRIX.ndim

2

In [10]:
MATRIX.shape

torch.Size([2, 2])

In [11]:
MATRIX[0]

tensor([7, 8])

In [12]:
MATRIX[1]

tensor([6, 9])

In [13]:
# TENSOR

TENSOR = torch.tensor([[[1, 2, 3],
                        [4, 5, 6]],
                       [[7, 8, 9],
                        [10, 11, 12]]])
TENSOR

tensor([[[ 1,  2,  3],
         [ 4,  5,  6]],

        [[ 7,  8,  9],
         [10, 11, 12]]])

In [14]:
TENSOR.ndim

3

In [15]:
TENSOR.shape

torch.Size([2, 2, 3])

In [16]:
TENSOR[0]

tensor([[1, 2, 3],
        [4, 5, 6]])

In [17]:
TENSOR[1]

tensor([[ 7,  8,  9],
        [10, 11, 12]])

### Random tensors



In [18]:
X = torch.rand(3, 4)
X

tensor([[0.6763, 0.6084, 0.8592, 0.6633],
        [0.3008, 0.4662, 0.1345, 0.8623],
        [0.5626, 0.0542, 0.1665, 0.8531]])

In [19]:
X.ndim

2

In [20]:
X.shape

torch.Size([3, 4])

In [21]:
Y = torch.rand(size=(3, 32, 32))

In [22]:
Y.ndim

3

In [23]:
Y.shape

torch.Size([3, 32, 32])

### Zeros and Ones

In [24]:
zeros = torch.zeros(size=(3, 6))
zeros

tensor([[0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.]])

In [25]:
ones = torch.ones(size=(2, 8))
ones

tensor([[1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1.]])

In [26]:
ones.dtype

torch.float32

### Range of tensors

In [27]:
Z = torch.arange(start=0, end=11, step=2)
Z

tensor([ 0,  2,  4,  6,  8, 10])

### Datatypes

In [28]:
A = torch.tensor([1.0, 2.0], dtype=torch.half)

In [29]:
A.dtype

torch.float16

In [30]:
# float16 == torch.half
# float32 == torch.float
# float64 == torch.double

### Tensor Operations

In [37]:
X = torch.tensor([1, 2, 3])

In [38]:
X += 10

In [39]:
X

tensor([11, 12, 13])

In [40]:
X *= 10

In [41]:
X

tensor([110, 120, 130])

In [42]:
X -= 10

In [43]:
X

tensor([100, 110, 120])

In [46]:
A = torch.tensor([[1, 2],
                  [3, 4]])

In [47]:
A

tensor([[1, 2],
        [3, 4]])

In [48]:
B = torch.tensor([[5, 6],
                  [7, 8]])

In [49]:
B

tensor([[5, 6],
        [7, 8]])

In [53]:
A * B # elementwise multiplication

tensor([[ 5, 12],
        [21, 32]])

In [55]:
torch.matmul(A, B) # matrix multiplication

tensor([[19, 22],
        [43, 50]])

In [64]:
torch.mm(A, B) # shorthand name

tensor([[19, 22],
        [43, 50]])

In [56]:
A @ B

tensor([[19, 22],
        [43, 50]])

In [60]:
%%time
A @ B

CPU times: user 176 µs, sys: 11 µs, total: 187 µs
Wall time: 127 µs


tensor([[19, 22],
        [43, 50]])

In [61]:
%%time
torch.matmul(A, B)

CPU times: user 170 µs, sys: 10 µs, total: 180 µs
Wall time: 118 µs


tensor([[19, 22],
        [43, 50]])

In [63]:
# The time is almost same as '@' is an alternate.

### Aggregation functions

In [70]:
torch.min(A) # or A.min()

tensor(1)

In [71]:
torch.max(A) # or A.max()

tensor(4)

#### Code:

```
torch.mean(A)
```
#### Error:

RuntimeError                              Traceback (most recent call last)
/tmp/ipython-input-3715754511.py in <cell line: 0>()
----> 1 torch.mean(A)

RuntimeError: mean(): could not infer output dtype. Input dtype must be either a floating point or complex dtype. Got: Long

In [76]:
A = A.to(torch.float)

In [79]:
torch.mean(A) # or A.mean()

tensor(2.5000)

In [81]:
torch.sum(A) # or A.sum()

tensor(10.)

In [87]:
torch.argmin(A) # or A.argmin()

tensor(0)

In [88]:
torch.argmax(A) # or A.argmax()

tensor(3)

### Reshaping, Stacking, Squeezing, and Unsqueezing tensors

In [90]:
X = torch.arange(1, 10, dtype=torch.float)

In [91]:
X

tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [92]:
X.reshape(3, 3)

tensor([[1., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.]])

In [93]:
X.reshape(9, 1)

tensor([[1.],
        [2.],
        [3.],
        [4.],
        [5.],
        [6.],
        [7.],
        [8.],
        [9.]])

In [98]:
X.view(1, 3, 3) # view of a tensor shares the same memory
                # with the input, so if I allocate X.view(1, 3,
                # 3) to a new variable Z. If I make a change to
                # Z, X will also change. Reshape doesn't do that!

tensor([[[1., 2., 3.],
         [4., 5., 6.],
         [7., 8., 9.]]])

In [101]:
torch.stack([X, X], dim=0)

tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.],
        [1., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [102]:
torch.stack([X, X], dim=1)

tensor([[1., 1.],
        [2., 2.],
        [3., 3.],
        [4., 4.],
        [5., 5.],
        [6., 6.],
        [7., 7.],
        [8., 8.],
        [9., 9.]])

In [103]:
Z = X.reshape(1, 3, 3)

In [106]:
torch.stack([Z, Z], dim=2)

tensor([[[[1., 2., 3.],
          [1., 2., 3.]],

         [[4., 5., 6.],
          [4., 5., 6.]],

         [[7., 8., 9.],
          [7., 8., 9.]]]])

In [107]:
torch.hstack([X, X])

tensor([1., 2., 3., 4., 5., 6., 7., 8., 9., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [110]:
torch.vstack([X, X])

tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.],
        [1., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [125]:
C = X.reshape([1, 9])

In [126]:
C.shape

torch.Size([1, 9])

In [127]:
squeezed_C = C.squeeze()

In [128]:
squeezed_C.shape

torch.Size([9])

In [130]:
squeezed_C

tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [135]:
unsqueezed_C = squeezed_C.unsqueeze(dim=1)

In [136]:
unsqueezed_C.shape

torch.Size([9, 1])

In [137]:
unsqueezed_C

tensor([[1.],
        [2.],
        [3.],
        [4.],
        [5.],
        [6.],
        [7.],
        [8.],
        [9.]])

In [141]:
D = torch.rand(size=(64, 32, 3))

In [144]:
torch.permute(D, (2, 0, 1)).shape

torch.Size([3, 64, 32])

In [145]:
# permute returns a view of rearanged dimensions as specified.