<a href="https://colab.research.google.com/github/BilalAsifB/Learning-PyTorch/blob/main/notebooks/00_pytorch_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import torch
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
print(torch.__version__)

2.9.0+cpu


### Creating Tensors

In [3]:
# scalar

scalar = torch.tensor(7)
scalar

tensor(7)

In [4]:
scalar.ndim

0

In [5]:
scalar.item()

7

In [9]:
# vector

vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [10]:
vector.ndim

1

In [11]:
vector.shape

torch.Size([2])

In [12]:
# MATRIX

MATRIX = torch.tensor([[7, 8],
                       [6, 9]])
MATRIX

tensor([[7, 8],
        [6, 9]])

In [13]:
MATRIX.ndim

2

In [14]:
MATRIX.shape

torch.Size([2, 2])

In [16]:
MATRIX[0]

tensor([7, 8])

In [18]:
MATRIX[1]

tensor([6, 9])

In [24]:
# TENSOR

TENSOR = torch.tensor([[[1, 2, 3],
                        [4, 5, 6]],
                       [[7, 8, 9],
                        [10, 11, 12]]])
TENSOR

tensor([[[ 1,  2,  3],
         [ 4,  5,  6]],

        [[ 7,  8,  9],
         [10, 11, 12]]])

In [25]:
TENSOR.ndim

3

In [26]:
TENSOR.shape

torch.Size([2, 2, 3])

In [30]:
TENSOR[0]

tensor([[1, 2, 3],
        [4, 5, 6]])

In [31]:
TENSOR[1]

tensor([[ 7,  8,  9],
        [10, 11, 12]])

### Random tensors



In [33]:
X = torch.rand(3, 4)
X

tensor([[0.8638, 0.5228, 0.2908, 0.7732],
        [0.8322, 0.8491, 0.1980, 0.7727],
        [0.4885, 0.1340, 0.2110, 0.6359]])

In [34]:
X.ndim

2

In [35]:
X.shape

torch.Size([3, 4])

In [40]:
Y = torch.rand(size=(3, 32, 32))

In [41]:
Y.ndim

3

In [42]:
Y.shape

torch.Size([3, 32, 32])

### Zeros and Ones

In [57]:
zeros = torch.zeros(size=(3, 6))
zeros

tensor([[0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.]])

In [59]:
ones = torch.ones(size=(2, 8))
ones

tensor([[1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1.]])

In [61]:
ones.dtype

torch.float32

### Range of tensors

In [67]:
Z = torch.arange(start=0, end=11, step=2)
Z

tensor([ 0,  2,  4,  6,  8, 10])

### Datatypes

In [75]:
A = torch.tensor([1.0, 2.0], dtype=torch.half)

In [76]:
A.dtype

torch.float16

In [78]:
# float16 == torch.half
# float32 == torch.float
# float64 == torch.double